version: '3.8'
services:
  mongo:
    image: mongo
    ports:
      - "27017:27017"
  app:
    build: .
    ports:
      - "8080:80"
    depends_on:
      - mongo
    environment:
      - MONGO_URI=mongodb://mongo:27017
